version: "3"
volumes:
  db:
services:
  app:
    build: .
    ports:
    - "5000:5000"
    environment:
      DB_PASSWORD: example
    depends_on:
      - db


  db:
    image: mysql:8.0.25
    volumes:
    - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d

    environment:
      MYSQL_ROOT_PASSWORD: example

    ports:
    - "8080:3306"