"""empty message

Revision ID: bd0b71dea7a2
Revises: 0c5346df62d4
Create Date: 2021-06-04 20:38:23.877085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0b71dea7a2'
down_revision = '0c5346df62d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_history', sa.Column('description', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_history', 'description')
    # ### end Alembic commands ###
